uploads = []

[[generated]]
id = "elHinhS7tRE-GFkqUzO5R"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "chandmod moon icon"

[[outputs]]
id = "8pjKCTL9V6lBM7SUeoe_2"
uri = "file://chandmod-server.tar.gz"
type = "unspecified"
title = "ChandMod Server — chandtricker.qzz.io"

[[outputs]]
id = "ohi-gXrS5nAqoUqsOZXID"
uri = "file://chandmod-app.tar.gz"
type = "unspecified"
title = "ChandMod App — GitHub ke liye ready"
